include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - package
  - test-package
  - deploy

variables:
  STACK: static-pages

.deploy:
  environment:
    url: https://${DD_STATIC_SUBDOMAIN}.${PUBLIC_HOSTNAME}
