version: '3.5'

services:
  static-pages:
    networks:
      - traefik-net
    deploy:
      mode: global
      labels:
        traefik.docker.network: traefik-net
        traefik.static.port: "${INTERNAL_PORT}"
        traefik.static.frontend.rule: Host:${STATIC_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.static.backend: static-pages
        traefik.error-handle.port: "${INTERNAL_PORT}"
        traefik.error-handle.frontend.rule: Host:${PUBLIC_HOSTNAME};PathPrefixStripRegex:/{.*};AddPrefix:/50x/
        traefik.error-handle.frontend.priority: "1"
        traefik.error-handle.backend: static-pages
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          memory: 10M

networks:
  traefik-net:
    external: true
