services:
  static-pages:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/static-pages}:${IMAGE_TAG:-latest}
    networks:
      traefik-net:
    deploy:
      mode: global
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.services.static-pages.loadbalancer.server.port: 80

        traefik.http.routers.static-pages.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.static-pages.rule: Host(`${STATIC_SUBDOMAIN:-static}.${PUBLIC_HOSTNAME}`)

        traefik.http.routers.static-pages-ecomarcan-replacement.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.static-pages-ecomarcan-replacement.rule: Host(`${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.static-pages-ecomarcan-replacepathregex.replacepathregex.regex: ^.*?(resources/[^/]+\.\w+)?$$
        traefik.http.middlewares.static-pages-ecomarcan-replacepathregex.replacepathregex.replacement: /maintenance/$$1
        traefik.http.routers.static-pages-ecomarcan-replacement.middlewares: static-pages-ecomarcan-replacepathregex
        traefik.http.routers.static-pages-ecomarcan-replacement.priority: '1'
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
