version: '3.5'

services:
  static-pages:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/static-pages}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NGINX_IMAGE_TAG:
    networks:
      traefik-net:
    deploy:
      mode: global
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.static.frontend.rule: Host:${STATIC_SUBDOMAIN:-static}.${PUBLIC_HOSTNAME}
        traefik.web-error-handle.frontend.rule: Host:${PUBLIC_HOSTNAME};ReplacePathRegex:^.*?(resources/[^/]+\\.\\w+)?$$ /maintenance/$$1
        traefik.web-error-handle.frontend.priority: '1'
        traefik.old-viewer.frontend.rule: Host:www.redmic.es;PathPrefix:/flexviewers/visor
        traefik.old-viewer.frontend.redirect.regex: ^.*$$
        traefik.old-viewer.frontend.redirect.replacement: https://${PUBLIC_HOSTNAME}/atlas
        traefik.backend: ${BACKEND_NAME:-static-pages}
        traefik.port: '${PORT:-80}'
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-4M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
