version: '3.5'

services:
  static-pages:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    networks:
      - traefik-net
    healthcheck:
      test: wget --spider -q http://localhost
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: global
      labels:
        traefik.static.frontend.rule: Host:${STATIC_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.static.backend: static-pages
        traefik.static.port: "${INTERNAL_PORT}"
        traefik.web-error-handle.frontend.rule: Host:${PUBLIC_HOSTNAME};ReplacePathRegex:^.*?(resources/[^/]+\\.\\w+)?$$ /maintenance/$$1
        traefik.web-error-handle.frontend.priority: '1'
        traefik.web-error-handle.backend: static-pages
        traefik.web-error-handle.port: "${INTERNAL_PORT}"
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          memory: 52M

networks:
  traefik-net:
    external: true
