version: '3.9'

services:
  static-pages:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/static-pages}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NGINX_IMAGE_TAG:
    networks:
      traefik-net:
    deploy:
      mode: global
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'

        traefik.http.routers.static-pages.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.static-pages.rule: Host(`${STATIC_SUBDOMAIN:-static}.${PUBLIC_HOSTNAME}`)

        traefik.http.routers.static-pages-redmic-web-error.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.static-pages-redmic-web-error.rule: Host(`${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.static-pages-redmic-web-error-replacepathregex.replacepathregex.regex: ^.*?(resources/[^/]+\.\w+)?$$
        traefik.http.middlewares.static-pages-redmic-web-error-replacepathregex.replacepathregex.replacement: /maintenance/$$1
        traefik.http.routers.static-pages-redmic-web-error.middlewares: static-pages-redmic-web-error-replacepathregex
        traefik.http.routers.static-pages-redmic-web-error.priority: '1'

        traefik.http.services.static-pages.loadbalancer.server.port: 80
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-4M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
